# Generated by Django 5.1.4 on 2025-01-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='HTML-контент')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статистики')),
                ('description', models.TextField(verbose_name='Описание статистики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение статистики')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('key_skills', models.TextField(blank=True, verbose_name='Ключевые навыки')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=255, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата в рублях')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Валюта')),
                ('currency_exchange_rate', models.FloatField(blank=True, null=True, verbose_name='Курс валюты')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_dynamics', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата в рублях')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_city', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Данные таблицы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение таблицы')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
        migrations.CreateModel(
            name='TopSkillsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('frequency', models.IntegerField(verbose_name='Частота появления навыка')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_skills_by_year', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDynamics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_dynamics', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyShareByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('vacancy_share', models.FloatField(verbose_name='Доля вакансий')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_share_by_city', to='pages.statistics', verbose_name='Общая статистика')),
            ],
        ),
    ]
