# Generated by Django 5.1.4 on 2025-01-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта'),
        ),
    ]
