# Generated by Django 5.1.4 on 2025-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticstable',
            name='row_data',
            field=models.CharField(default='', max_length=255, verbose_name='Данные строки'),
        ),
    ]
