# Generated by Django 5.1.4 on 2025-01-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_statisticstable_row_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='description',
        ),
    ]
