# Generated by Django 5.1.4 on 2025-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_statistics_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticstable',
            name='row_data',
        ),
        migrations.RemoveField(
            model_name='statisticstable',
            name='table',
        ),
        migrations.AddField(
            model_name='statisticstable',
            name='column_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Колонка 1'),
        ),
        migrations.AddField(
            model_name='statisticstable',
            name='column_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Колонка 2'),
        ),
        migrations.AlterField(
            model_name='statisticstable',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название таблицы'),
        ),
    ]
