# Generated by Django 5.1.4 on 2025-01-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_statisticstable_row_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticstable',
            name='name',
        ),
    ]
