# Generated by Django 5.1.4 on 2025-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_statisticstable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticstable',
            name='table',
            field=models.TextField(blank=True, null=True, verbose_name='HTML таблицы'),
        ),
    ]
