# Generated by Django 5.1.4 on 2025-01-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_statisticstable_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticstable',
            name='image',
        ),
        migrations.RemoveField(
            model_name='statisticstable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='statisticstable',
            name='table',
        ),
    ]
