# Generated by Django 5.1.4 on 2025-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_statisticstable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Изображение статистики'),
        ),
    ]
