# Generated by Django 5.1.4 on 2025-01-15 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_geostatistics_geostatisticstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок статистики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Изображение статистики')),
            ],
        ),
        migrations.CreateModel(
            name='SkillStatisticsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.CharField(max_length=255, null=True, verbose_name='Колонка 1')),
                ('column_2', models.CharField(max_length=255, null=True, verbose_name='Колонка 2')),
                ('skillstatistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pages.skillstatistics', verbose_name='Навыки')),
            ],
        ),
    ]
